dir=/downloads
input-file=/config/aria2.session
save-session=/config/aria2.session
dht-file-path=/config/dht.dat

log-level=info

enable-rpc=true
disable-ipv6=true
rpc-allow-origin-all=true
rpc-secret=rpc-secret
rpc-listen-all=true
rpc-listen-port=6800

continue=true
max-concurrent-downloads=10
max-connection-per-server=8
min-split-size=10M
split=10
max-overall-download-limit=0
max-download-limit=0
max-overall-upload-limit=512
max-upload-limit=0
file-allocation=falloc
check-certificate=false

# BT
enable-dht=true
listen-port=51467
dht-listen-port=51467
bt-enable-lpd=true
enable-peer-exchange=true
bt-require-crypto=true
bt-force-encryption=true
bt-min-crypto-level=arc4
bt-max-open-files=2048
bt-max-peers=128
bt-request-peer-speed-limit=200K
follow-torrent=mem
seed-time=0
bt-seed-unverified=true
bt-save-metadata=false
bt-prioritize-piece=head
bt-stop-timeout=108000

user-agent=uTorrent/2210(25130) 
peer-id-prefix=-UT2210-

bt-tracker=udp://tracker.coppersurfer.tk:6969/announce
